<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Database\Database;

function getFacetAliases() {
  $connection = Database::getConnection();
  $like = $connection->escapeLike('search_api_db_facet_field_') . '%';
  $query = $connection->query("SHOW TABLE STATUS LIKE :like", [':like' => $like]);
  $tables = $query->fetchAllKeyed(0, 0);

  $facet_aliases = [];
  foreach ($tables as $table_name => $data) {
      if ($table_name !== 'search_api_db_facet_field_type') {
          $alias = str_replace('search_api_db_facet_field_', '', $table_name);
          $facet_aliases[] = $alias;
      }
  }

  return $facet_aliases;
}

/**
 * Implements hook_preprocess_page().
 */
function darth_views404_preprocess_page(&$variables) {
    $current_path = \Drupal::service('path.current')->getPath();
    $route_match = \Drupal::routeMatch();

    if (strpos($current_path, '/catalog/') !== FALSE) {
        if (isNodePage($route_match)) {
            return;
        }

        $facet_aliases = getFacetAliases();

        $path_parts = explode('/', trim($current_path, '/'));

        $facet_in_url = false;
        foreach ($facet_aliases as $alias) {
            if (in_array($alias, $path_parts)) {
                $facet_in_url = true;
                break;
            }
        }

        if (!$facet_in_url) {
          redirectTo404();
        }
    }
}


/**
 * 
 *
 * @param RouteMatchInterface $route_match
 * @return bool
 */
function isNodePage(RouteMatchInterface $route_match) {
    if ($route_match->getRouteName() == 'entity.node.canonical') {
        return TRUE;
    }

    return FALSE;
}

/**
 * 
 */
function redirectTo404() {
    $response = new RedirectResponse('/404', 301);
    $response->send();
    exit;
}
